#sudo bash ./observer.sh 0
#sudo bash ./observer.sh 1
#sudo bash ./observer.sh 2
#sudo bash ./observer.sh 3
#sudo bash ./observer.sh 4
#sudo bash ./observer.sh 5
#sudo bash ./observer.sh 6
#sudo bash ./observer.sh 7
#sudo bash ./observer.sh 8
#sudo bash ./observer.sh 9
#sudo bash ./observer.sh 10
#sudo bash ./observer.sh 11
#sudo bash ./observer.sh 12
#sudo bash ./observer.sh 13
#sudo bash ./observer.sh 14
#sudo bash ./observer.sh 15
#sudo bash ./observer.sh 16
#sudo bash ./observer.sh 17
#sudo bash ./observer.sh 18
#sudo bash ./observer.sh 19
#sudo bash ./observer.sh 20
#sudo bash ./observer.sh 21
#sudo bash ./observer.sh 22
#sudo bash ./observer.sh 23
#sudo bash ./observer.sh 24
#sudo bash ./observer.sh 25
#sudo bash ./observer.sh 26
#sudo bash ./observer.sh 27
#sudo bash ./observer.sh 28
#sudo bash ./observer.sh 29
#sudo bash ./observer.sh 30
#sudo bash ./observer.sh 31
sudo bash ./observer.sh 32
sudo bash ./observer.sh 33
sudo bash ./observer.sh 34
sudo bash ./observer.sh 35
sudo bash ./observer.sh 36
sudo bash ./observer.sh 37
sudo bash ./observer.sh 38
sudo bash ./observer.sh 39
sudo bash ./observer.sh 40
sudo bash ./observer.sh 41
sudo bash ./observer.sh 42
sudo bash ./observer.sh 43
sudo bash ./observer.sh 44
sudo bash ./observer.sh 45
sudo bash ./observer.sh 46
sudo bash ./observer.sh 47
sudo bash ./observer.sh 48
sudo bash ./observer.sh 49
sudo bash ./observer.sh 50
sudo bash ./observer.sh 51
sudo bash ./observer.sh 52
sudo bash ./observer.sh 53
sudo bash ./observer.sh 54
sudo bash ./observer.sh 55
sudo bash ./observer.sh 56
sudo bash ./observer.sh 57
sudo bash ./observer.sh 58
sudo bash ./observer.sh 59
sudo bash ./observer.sh 60
sudo bash ./observer.sh 61
sudo bash ./observer.sh 62
sudo bash ./observer.sh 63
sudo bash ./observer.sh 64
sudo bash ./observer.sh 65
sudo bash ./observer.sh 66
sudo bash ./observer.sh 67
sudo bash ./observer.sh 68
sudo bash ./observer.sh 69
sudo bash ./observer.sh 70
sudo bash ./observer.sh 71
sudo bash ./observer.sh 72
sudo bash ./observer.sh 73
sudo bash ./observer.sh 74
sudo bash ./observer.sh 75
sudo bash ./observer.sh 76
sudo bash ./observer.sh 77
sudo bash ./observer.sh 78
sudo bash ./observer.sh 79
sudo bash ./observer.sh 80
sudo bash ./observer.sh 81
sudo bash ./observer.sh 82
sudo bash ./observer.sh 83
sudo bash ./observer.sh 84
sudo bash ./observer.sh 85
sudo bash ./observer.sh 86
sudo bash ./observer.sh 87
sudo bash ./observer.sh 88
sudo bash ./observer.sh 89
sudo bash ./observer.sh 90
sudo bash ./observer.sh 91
sudo bash ./observer.sh 92
sudo bash ./observer.sh 93
sudo bash ./observer.sh 94
sudo bash ./observer.sh 95
sudo bash ./observer.sh 96
sudo bash ./observer.sh 97
sudo bash ./observer.sh 98
sudo bash ./observer.sh 99
sudo bash ./observer.sh 100
sudo bash ./observer.sh 101
sudo bash ./observer.sh 102
sudo bash ./observer.sh 103
sudo bash ./observer.sh 104
sudo bash ./observer.sh 105
sudo bash ./observer.sh 106
sudo bash ./observer.sh 107
sudo bash ./observer.sh 108
sudo bash ./observer.sh 109
